# Set up download directories
source ../DCENT_config.sh
export dir_list_file="../dir_list.txt"
dir_download=$(grep "others" "$dir_list_file" | head -n 1)

export HadCRUT5_version="5.0.2.0"

# Download HadCRUT5 ---------------------------------------------------------
export dir_remote="https://www.metoffice.gov.uk/hadobs/hadcrut5/data/HadCRUT."${HadCRUT5_version}"/non-infilled/"
export dir_local=${dir_download}"/HadCRUT5/"
mkdir -p ${dir_local}
fname="HadCRUT."${HadCRUT5_version}".anomalies.ensemble_mean.nc"
echo $dir_local$fname
echo $dir_remote$fname
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".weights.nc"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".uncorrelated.nc"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.1_to_10_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.11_to_20_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.21_to_30_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.31_to_40_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.41_to_50_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.51_to_60_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.61_to_70_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.71_to_80_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.81_to_90_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.91_to_100_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.101_to_110_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.111_to_120_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.121_to_130_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.131_to_140_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.141_to_150_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.151_to_160_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.161_to_170_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.171_to_180_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.181_to_190_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".anomalies.191_to_200_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
export dir_remote="https://www.metoffice.gov.uk/hadobs/hadcrut5/data/HadCRUT."${HadCRUT5_version}"/non-infilled/error_covariance/"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1850_to_1859.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1860_to_1869.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1870_to_1879.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1880_to_1889.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1890_to_1899.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1900_to_1909.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1910_to_1919.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1920_to_1929.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1930_to_1939.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1940_to_1949.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1950_to_1959.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1960_to_1969.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1970_to_1979.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1980_to_1989.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.1990_to_1999.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.2000_to_2009.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.2010_to_2019.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".error_covariance.2020_to_2029.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"

mkdir -p ${dir_local}/HadCRUT5_ensemble/
mkdir -p ${dir_local}/HadCRUT5_error_covariance/
rm -rf ${dir_local}/HadCRUT5_ensemble/*
rm -rf ${dir_local}/HadCRUT5_error_covariance/*
unzip "${dir_local}HadCRUT.${HadCRUT5_version}.anomalies.*_to_*_netcdf.zip" -d "${dir_local}HadCRUT5_ensemble/"
unzip "${dir_local}HadCRUT.${HadCRUT5_version}.error_covariance.*_to_*.zip" -d "${dir_local}HadCRUT5_error_covariance/"
rm ${dir_local}*.zip

# Download HadCRUT5 infilled analysis ---------------------------------------------------------
export dir_remote="https://www.metoffice.gov.uk/hadobs/hadcrut5/data/HadCRUT."${HadCRUT5_version}"/analysis/"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.ensemble_mean.nc"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.weights.nc"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.1_to_10_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.11_to_20_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.21_to_30_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.31_to_40_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.41_to_50_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.51_to_60_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.61_to_70_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.71_to_80_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.81_to_90_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.91_to_100_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.101_to_110_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.111_to_120_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.121_to_130_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.131_to_140_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.141_to_150_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.151_to_160_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.161_to_170_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.171_to_180_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.181_to_190_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"
fname="HadCRUT."${HadCRUT5_version}".analysis.anomalies.191_to_200_netcdf.zip"
curl -o "$dir_local$fname" "$dir_remote$fname"

mkdir -p ${dir_local}/HadCRUT5_analysis_ensemble/
rm -rf ${dir_local}/HadCRUT5_analysis_ensemble/*
unzip "${dir_local}HadCRUT.${HadCRUT5_version}.analysis.anomalies.*_to_*_netcdf.zip" -d "${dir_local}HadCRUT5_analysis_ensemble/"
rm ${dir_local}*.zip

